# docker-compose.yml

services:
  backend:
    build:
      context: ./backend
      platforms:
        - "linux/amd64"
    image: micobo/proyectogestionexamenes-backend:latest
    env_file:
      - .env
    environment:
      DOCKER_ENV: "true" # <--- AÑADE ESTA LÍNEA
    ports:
      - "3000:3000"
    volumes:
      - ./backend/wallet:/app/wallet
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      platforms:
        - "linux/amd64" # <-- Instrucción clave para compatibilidad
    image: micobo/proyectogestionexamenes-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
