-- ============================================================
-- SCRIPT COMPLETO DE CREACIÓN DE BASE DE DATOS
-- Sistema de Gestión de Exámenes
-- Generado: 2026-04-02
-- ============================================================
-- Ejecutar como usuario ADMIN en Oracle (Autonomous Database o XE)
-- ============================================================

-- ============================================================
-- 1. SECUENCIAS
-- ============================================================

CREATE SEQUENCE SEQ_SEDE       START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EDIFICIO   START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SALA       START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
-- SEQ_ESCUELA también usada para ESTADO
CREATE SEQUENCE SEQ_ESCUELA    START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CARRERA    START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ASIGNATURA START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_JORNADA    START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SECCION    START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROL        START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USUARIO    START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MODULO     START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EXAMEN     START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RESERVA_SEQ    START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PERMISOSROL START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN_ESTUDIO            START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CARRERA_PLAN_ESTUDIO    START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- 2. TABLAS
-- ============================================================

-- Entidades de Ubicación
CREATE TABLE SEDE (
    ID_SEDE       NUMBER NOT NULL,
    NOMBRE_SEDE   VARCHAR2(1020) NOT NULL,
    CONSTRAINT PK_SEDE PRIMARY KEY (ID_SEDE)
);

CREATE TABLE EDIFICIO (
    ID_EDIFICIO       NUMBER NOT NULL,
    NOMBRE_EDIFICIO   VARCHAR2(1020) NOT NULL,
    SIGLA_EDIFICIO    VARCHAR2(10) NOT NULL,
    SEDE_ID_SEDE      NUMBER NOT NULL,
    CONSTRAINT PK_EDIFICIO PRIMARY KEY (ID_EDIFICIO),
    CONSTRAINT FK_EDIFICIO_SEDE FOREIGN KEY (SEDE_ID_SEDE) REFERENCES SEDE(ID_SEDE)
);

CREATE TABLE SALA (
    ID_SALA               NUMBER NOT NULL,
    NOMBRE_SALA           VARCHAR2(1020) NOT NULL,
    CAPACIDAD_SALA        NUMBER NOT NULL,
    COD_SALA              VARCHAR2(20),
    EDIFICIO_ID_EDIFICIO  NUMBER NOT NULL,
    CONSTRAINT PK_SALA PRIMARY KEY (ID_SALA),
    CONSTRAINT FK_SALA_EDIFICIO FOREIGN KEY (EDIFICIO_ID_EDIFICIO) REFERENCES EDIFICIO(ID_EDIFICIO)
);

-- Entidades Académicas
CREATE TABLE ESCUELA (
    ID_ESCUELA                    NUMBER NOT NULL,
    NOMBRE_ESCUELA                VARCHAR2(1020) NOT NULL,
    FECHA_CREACION_ESCUELA        TIMESTAMP(0) NOT NULL,
    FECHA_ACTUALIZACION_ESCUELA   TIMESTAMP(0),
    SEDE_ID_SEDE                  NUMBER NOT NULL,
    COLOR_BACKGROUND              VARCHAR2(50),
    COLOR_BORDER                  VARCHAR2(50),
    CONSTRAINT PK_ESCUELA PRIMARY KEY (ID_ESCUELA),
    CONSTRAINT FK_ESCUELA_SEDE FOREIGN KEY (SEDE_ID_SEDE) REFERENCES SEDE(ID_SEDE)
);

CREATE TABLE ROL (
    ID_ROL      NUMBER NOT NULL,
    NOMBRE_ROL  VARCHAR2(400) NOT NULL,
    CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL)
);

CREATE TABLE USUARIO (
    ID_USUARIO          NUMBER NOT NULL,
    NOMBRE_USUARIO      VARCHAR2(1020) NOT NULL,
    EMAIL_USUARIO       VARCHAR2(1020) NOT NULL,
    PASSWORD_USUARIO    VARCHAR2(1020) NOT NULL,
    FECHA_CREA_USUARIO  TIMESTAMP(0) NOT NULL,
    FECHA_ACTU_USUARIO  TIMESTAMP(0),
    ROL_ID_ROL          NUMBER NOT NULL,
    ID_DOCENTE          NUMBER,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ROL_ID_ROL) REFERENCES ROL(ID_ROL)
);

CREATE TABLE CARRERA (
    ID_CARRERA          NUMBER NOT NULL,
    NOMBRE_CARRERA      VARCHAR2(1020) NOT NULL,
    ESCUELA_ID_ESCUELA  NUMBER NOT NULL,
    USUARIO_ID_USUARIO  NUMBER,
    CONSTRAINT PK_CARRERA PRIMARY KEY (ID_CARRERA),
    CONSTRAINT FK_CARRERA_ESCUELA FOREIGN KEY (ESCUELA_ID_ESCUELA) REFERENCES ESCUELA(ID_ESCUELA),
    CONSTRAINT FK_CARRERA_USUARIO FOREIGN KEY (USUARIO_ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE ASIGNATURA (
    ID_ASIGNATURA       NUMBER NOT NULL,
    NOMBRE_ASIGNATURA   VARCHAR2(1020) NOT NULL,
    CARRERA_ID_CARRERA  NUMBER NOT NULL,
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY (ID_ASIGNATURA),
    CONSTRAINT FK_ASIGNATURA_CARRERA FOREIGN KEY (CARRERA_ID_CARRERA) REFERENCES CARRERA(ID_CARRERA)
);

CREATE TABLE JORNADA (
    ID_JORNADA      NUMBER NOT NULL,
    NOMBRE_JORNADA  VARCHAR2(1020) NOT NULL,
    COD_JORNADA     VARCHAR2(2),
    CONSTRAINT PK_JORNADA PRIMARY KEY (ID_JORNADA)
);

CREATE TABLE SECCION (
    ID_SECCION                  NUMBER NOT NULL,
    NOMBRE_SECCION              VARCHAR2(1020) NOT NULL,
    ASIGNATURA_ID_ASIGNATURA    NUMBER NOT NULL,
    JORNADA_ID_JORNADA          NUMBER NOT NULL,
    CONSTRAINT PK_SECCION PRIMARY KEY (ID_SECCION),
    CONSTRAINT FK_SECCION_ASIGNATURA FOREIGN KEY (ASIGNATURA_ID_ASIGNATURA) REFERENCES ASIGNATURA(ID_ASIGNATURA),
    CONSTRAINT FK_SECCION_JORNADA FOREIGN KEY (JORNADA_ID_JORNADA) REFERENCES JORNADA(ID_JORNADA)
);

-- Permisos
CREATE TABLE PERMISOS (
    ID_PERMISO          NUMBER NOT NULL,
    NOMBRE_PERMISO      VARCHAR2(100) NOT NULL,
    DESCRIPCION_PERMISO VARCHAR2(255),
    GRUPO_PERMISO       VARCHAR2(100),
    CONSTRAINT PK_PERMISOS PRIMARY KEY (ID_PERMISO)
);

CREATE TABLE PERMISOSROL (
    ID_PERMISOSROL  NUMBER NOT NULL,
    ID_ROL          NUMBER NOT NULL,
    ID_PERMISO      NUMBER NOT NULL,
    CONSTRAINT PK_PERMISOSROL PRIMARY KEY (ID_PERMISOSROL),
    CONSTRAINT FK_PERMISOSROL_ROL    FOREIGN KEY (ID_ROL)     REFERENCES ROL(ID_ROL),
    CONSTRAINT FK_PERMISOSROL_PERM   FOREIGN KEY (ID_PERMISO) REFERENCES PERMISOS(ID_PERMISO)
);

-- Relaciones Usuario
CREATE TABLE USUARIOCARRERA (
    USUARIO_ID_USUARIO  NUMBER NOT NULL,
    CARRERA_ID_CARRERA  NUMBER NOT NULL,
    CONSTRAINT PK_USUARIOCARRERA PRIMARY KEY (USUARIO_ID_USUARIO, CARRERA_ID_CARRERA),
    CONSTRAINT FK_USRCARRERA_USR     FOREIGN KEY (USUARIO_ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_USRCARRERA_CARRERA FOREIGN KEY (CARRERA_ID_CARRERA) REFERENCES CARRERA(ID_CARRERA)
);

CREATE TABLE USUARIOSECCION (
    SECCION_ID_SECCION  NUMBER NOT NULL,
    USUARIO_ID_USUARIO  NUMBER NOT NULL,
    CONSTRAINT PK_USUARIOSECCION PRIMARY KEY (SECCION_ID_SECCION, USUARIO_ID_USUARIO),
    CONSTRAINT FK_USRSECCION_SECCION FOREIGN KEY (SECCION_ID_SECCION) REFERENCES SECCION(ID_SECCION),
    CONSTRAINT FK_USRSECCION_USR     FOREIGN KEY (USUARIO_ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- Planificación
CREATE TABLE ESTADO (
    ID_ESTADO      NUMBER NOT NULL,
    NOMBRE_ESTADO  VARCHAR2(1020) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO)
);

CREATE TABLE MODULO (
    ID_MODULO         NUMBER NOT NULL,
    NOMBRE_MODULO     VARCHAR2(1020) NOT NULL,
    INICIO_MODULO     VARCHAR2(5) NOT NULL,
    FIN_MODULO        VARCHAR2(5) NOT NULL,
    ORDEN             NUMBER NOT NULL,
    ESTADO_ID_ESTADO  NUMBER NOT NULL,
    CONSTRAINT PK_MODULO PRIMARY KEY (ID_MODULO),
    CONSTRAINT UQ_MODULO_ORDEN UNIQUE (ORDEN),
    CONSTRAINT FK_MODULO_ESTADO FOREIGN KEY (ESTADO_ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE EXAMEN (
    ID_EXAMEN                       NUMBER NOT NULL,
    NOMBRE_EXAMEN                   VARCHAR2(1020) NOT NULL,
    INSCRITOS_EXAMEN                NUMBER NOT NULL,
    TIPO_PROCESAMIENTO_EXAMEN       VARCHAR2(1020) NOT NULL,
    PLATAFORMA_PROSE_EXAMEN         VARCHAR2(1020) NOT NULL,
    SITUACION_EVALUATIVA_EXAMEN     VARCHAR2(1020) NOT NULL,
    CANTIDAD_MODULOS_EXAMEN         NUMBER NOT NULL,
    SECCION_ID_SECCION              NUMBER NOT NULL,
    ESTADO_ID_ESTADO                NUMBER NOT NULL,
    ID_EVENTO                       NUMBER,
    CONSTRAINT PK_EXAMEN PRIMARY KEY (ID_EXAMEN),
    CONSTRAINT FK_EXAMEN_SECCION FOREIGN KEY (SECCION_ID_SECCION) REFERENCES SECCION(ID_SECCION),
    CONSTRAINT FK_EXAMEN_ESTADO  FOREIGN KEY (ESTADO_ID_ESTADO)   REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE RESERVA (
    ID_RESERVA                      NUMBER NOT NULL,
    FECHA_RESERVA                   TIMESTAMP(0) NOT NULL,
    SALA_ID_SALA                    NUMBER NOT NULL,
    EXAMEN_ID_EXAMEN                NUMBER NOT NULL,
    ESTADO_ID_ESTADO                NUMBER NOT NULL,
    ESTADO_CONFIRMACION_DOCENTE     VARCHAR2(20)  DEFAULT 'PENDIENTE',
    OBSERVACIONES_DOCENTE           VARCHAR2(1020),
    FECHA_CONFIRMACION_DOCENTE      TIMESTAMP(0),
    CONSTRAINT PK_RESERVA PRIMARY KEY (ID_RESERVA),
    CONSTRAINT FK_RESERVA_SALA   FOREIGN KEY (SALA_ID_SALA)        REFERENCES SALA(ID_SALA),
    CONSTRAINT FK_RESERVA_EXAMEN FOREIGN KEY (EXAMEN_ID_EXAMEN)    REFERENCES EXAMEN(ID_EXAMEN),
    CONSTRAINT FK_RESERVA_ESTADO FOREIGN KEY (ESTADO_ID_ESTADO)    REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE RESERVAMODULO (
    MODULO_ID_MODULO    NUMBER NOT NULL,
    RESERVA_ID_RESERVA  NUMBER NOT NULL,
    CONSTRAINT PK_RESERVAMODULO PRIMARY KEY (MODULO_ID_MODULO, RESERVA_ID_RESERVA),
    CONSTRAINT FK_RESMOD_MODULO  FOREIGN KEY (MODULO_ID_MODULO)   REFERENCES MODULO(ID_MODULO),
    CONSTRAINT FK_RESMOD_RESERVA FOREIGN KEY (RESERVA_ID_RESERVA) REFERENCES RESERVA(ID_RESERVA)
);

-- Tabla nueva: docentes asignados a reservas
CREATE TABLE RESERVA_DOCENTES (
    RESERVA_ID_RESERVA  NUMBER NOT NULL,
    USUARIO_ID_USUARIO  NUMBER NOT NULL,
    CONSTRAINT PK_RESERVA_DOCENTES PRIMARY KEY (RESERVA_ID_RESERVA, USUARIO_ID_USUARIO),
    CONSTRAINT FK_RESDOC_RESERVA FOREIGN KEY (RESERVA_ID_RESERVA) REFERENCES RESERVA(ID_RESERVA),
    CONSTRAINT FK_RESDOC_USUARIO FOREIGN KEY (USUARIO_ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- ============================================================
-- 3. DATOS DE CATÁLOGO (ESTADO)
-- ID=1 debe ser ACTIVO (hardcodeado en el backend)
-- ============================================================

INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (1, 'ACTIVO');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (2, 'DESCARTADO');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (3, 'PENDIENTE');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (4, 'CONFIRMADO');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (5, 'FINALIZADO');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (6, 'RESERVADO');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (7, 'PROGRAMADO');

-- ============================================================
-- 4. ROLES
-- ID=2 → Docente, ID=3 → Alumno (hardcodeados en el backend)
-- ============================================================

INSERT INTO ROL (ID_ROL, NOMBRE_ROL) VALUES (1, 'Administrador');
INSERT INTO ROL (ID_ROL, NOMBRE_ROL) VALUES (2, 'Docente');
INSERT INTO ROL (ID_ROL, NOMBRE_ROL) VALUES (3, 'Alumno');

-- ============================================================
-- 5. JORNADAS
-- ============================================================

INSERT INTO JORNADA (ID_JORNADA, NOMBRE_JORNADA, COD_JORNADA) VALUES (1, 'Diurna',     'DI');
INSERT INTO JORNADA (ID_JORNADA, NOMBRE_JORNADA, COD_JORNADA) VALUES (2, 'Vespertina', 'VE');
INSERT INTO JORNADA (ID_JORNADA, NOMBRE_JORNADA, COD_JORNADA) VALUES (3, 'Nocturna',   'NO');

-- ============================================================
-- 6. MÓDULOS HORARIOS (horario académico estándar)
-- ============================================================

INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (1,  'Módulo 1',  '08:00', '08:45', 1,  1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (2,  'Módulo 2',  '08:45', '09:30', 2,  1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (3,  'Módulo 3',  '09:30', '10:15', 3,  1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (4,  'Módulo 4',  '10:30', '11:15', 4,  1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (5,  'Módulo 5',  '11:15', '12:00', 5,  1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (6,  'Módulo 6',  '12:00', '12:45', 6,  1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (7,  'Módulo 7',  '14:00', '14:45', 7,  1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (8,  'Módulo 8',  '14:45', '15:30', 8,  1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (9,  'Módulo 9',  '15:30', '16:15', 9,  1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (10, 'Módulo 10', '16:30', '17:15', 10, 1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (11, 'Módulo 11', '17:15', '18:00', 11, 1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (12, 'Módulo 12', '18:00', '18:45', 12, 1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (13, 'Módulo 13', '19:00', '19:45', 13, 1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (14, 'Módulo 14', '19:45', '20:30', 14, 1);
INSERT INTO MODULO (ID_MODULO, NOMBRE_MODULO, INICIO_MODULO, FIN_MODULO, ORDEN, ESTADO_ID_ESTADO) VALUES (15, 'Módulo 15', '20:30', '21:15', 15, 1);

-- ============================================================
-- 7. PERMISOS
-- Nombres exactos usados en las rutas del backend
-- ============================================================

-- Grupo: CARRERAS
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (1,  'VER CARRERAS',        'Ver listado de carreras',          'CARRERAS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (2,  'CREAR CARRERAS',      'Crear nuevas carreras',            'CARRERAS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (3,  'ACTUALIZAR CARRERAS', 'Editar carreras existentes',       'CARRERAS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (4,  'ELIMINAR CARRERAS',   'Eliminar carreras',                'CARRERAS');

-- Grupo: EXAMENES
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (5,  'VER EXAMENES',        'Ver listado de exámenes',          'EXAMENES');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (6,  'CREAR EXAMENES',      'Crear nuevos exámenes',            'EXAMENES');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (7,  'EDITAR EXAMENES',     'Editar exámenes existentes',       'EXAMENES');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (8,  'ELIMINAR EXAMENES',   'Eliminar exámenes',                'EXAMENES');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (9,  'VIEW_EXAMEN_DETAIL',  'Ver detalle completo de un examen','EXAMENES');

-- Grupo: RESERVAS
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (10, 'VER TODAS LAS RESERVA',             'Ver todas las reservas del sistema',       'RESERVAS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (11, 'CREAR RESERVA EXAMEN',              'Crear reservas de sala para exámenes',     'RESERVAS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (12, 'EDITAR RESERVA',                    'Editar reservas existentes',               'RESERVAS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (13, 'ELIMINAR RESERVA',                  'Eliminar reservas',                        'RESERVAS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (14, 'VER DETALLE RESERVA',               'Ver detalle de una reserva',               'RESERVAS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (15, 'ACTUALIZAR_CONFIRMACION_RESERVA',   'Confirmar o rechazar reserva (docente)',   'RESERVAS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (16, 'VER RESERVAS PENDIENTES DOCENTE',   'Ver reservas pendientes de confirmación',  'RESERVAS');

-- Grupo: USUARIOS
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (17, 'VER USUARIOS',    'Ver listado de usuarios',    'USUARIOS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (18, 'CREAR USUARIOS',  'Crear nuevos usuarios',      'USUARIOS');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (19, 'ELIMINAR USUARIOS','Eliminar usuarios',          'USUARIOS');

-- Grupo: ROLES
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (20, 'VER ROLES',       'Ver listado de roles',              'ROLES');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (21, 'CREAR ROLES',     'Crear nuevos roles',                'ROLES');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (22, 'EDITAR ROLES',    'Editar roles existentes',           'ROLES');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (23, 'ELIMINAR ROLES',  'Eliminar roles',                    'ROLES');
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (24, 'VIEW_ROL_DETAIL', 'Ver detalle completo de un rol',    'ROLES');

-- Grupo: DASHBOARD
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (25, 'VER DASHBOARD',      'Ver el dashboard principal',      'DASHBOARD');

-- Grupo: CALENDARIO
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (26, 'VER CALENDARIO',     'Ver calendario de exámenes',      'CALENDARIO');

-- Grupo: ASIGNATURAS
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (27, 'VER ASIGNATURAS',    'Ver listado de asignaturas',      'ASIGNATURAS');

-- Grupo: SALAS
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (28, 'VER SALAS',          'Ver listado de salas',            'SALAS');

-- Grupo: MODULOS
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (29, 'VER MODULOS',        'Ver listado de módulos',          'MODULOS');

-- Grupo: CARGA
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (30, 'VER CARGA DE DATOS', 'Acceder a carga masiva de datos', 'CARGA');

-- Grupo: REPORTES
INSERT INTO PERMISOS (ID_PERMISO, NOMBRE_PERMISO, DESCRIPCION_PERMISO, GRUPO_PERMISO) VALUES (31, 'VER REPORTES',       'Ver reportes del sistema',        'REPORTES');

-- ============================================================
-- 8. PERMISOS DEL ROL ADMINISTRADOR (ID_ROL = 1) → todos los permisos
-- ============================================================

INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (1,  1, 1);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (2,  1, 2);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (3,  1, 3);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (4,  1, 4);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (5,  1, 5);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (6,  1, 6);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (7,  1, 7);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (8,  1, 8);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (9,  1, 9);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (10, 1, 10);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (11, 1, 11);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (12, 1, 12);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (13, 1, 13);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (14, 1, 14);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (15, 1, 15);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (16, 1, 16);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (17, 1, 17);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (18, 1, 18);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (19, 1, 19);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (20, 1, 20);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (21, 1, 21);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (22, 1, 22);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (23, 1, 23);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (24, 1, 24);
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (25, 1, 25);
INSERT INTO PERMISOSROL (ID_ROL, ID_PERMISO) VALUES (1, 26);
INSERT INTO PERMISOSROL (ID_ROL, ID_PERMISO) VALUES (1, 27);
INSERT INTO PERMISOSROL (ID_ROL, ID_PERMISO) VALUES (1, 28);
INSERT INTO PERMISOSROL (ID_ROL, ID_PERMISO) VALUES (1, 29);
INSERT INTO PERMISOSROL (ID_ROL, ID_PERMISO) VALUES (1, 30);
INSERT INTO PERMISOSROL (ID_ROL, ID_PERMISO) VALUES (1, 31);

-- Permisos del Rol Docente (ID_ROL = 2)
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (26, 2, 5);   -- VER EXAMENES
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (27, 2, 9);   -- VIEW_EXAMEN_DETAIL
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (28, 2, 14);  -- VER DETALLE RESERVA
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (29, 2, 15);  -- ACTUALIZAR_CONFIRMACION_RESERVA
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (30, 2, 16);  -- VER RESERVAS PENDIENTES DOCENTE
INSERT INTO PERMISOSROL (ID_PERMISOSROL, ID_ROL, ID_PERMISO) VALUES (31, 2, 25);  -- VER DASHBOARD

-- ============================================================
-- 9. USUARIO ADMINISTRADOR
-- Email: admin@examenes.cl
-- Password: Admin123.  (bcrypt 10 rounds)
-- ============================================================

INSERT INTO USUARIO (
    ID_USUARIO,
    NOMBRE_USUARIO,
    EMAIL_USUARIO,
    PASSWORD_USUARIO,
    FECHA_CREA_USUARIO,
    FECHA_ACTU_USUARIO,
    ROL_ID_ROL
) VALUES (
    1,
    'Administrador',
    'admin@examenes.cl',
    '$2b$10$GEb6uLqJynIbwDqYyo6g4.yp3i9TPzdb203dH29G/vjCyghJVwUHa',
    SYSTIMESTAMP,
    SYSTIMESTAMP,
    1
);

COMMIT;

-- ============================================================
-- 10. TABLAS COMPLEMENTARIAS
-- ============================================================

CREATE TABLE PLAN_ESTUDIO (
    ID_PLAN_ESTUDIO       NUMBER NOT NULL,
    NOMBRE_PLAN_ESTUDIO   VARCHAR2(200) NOT NULL,
    CONSTRAINT PK_PLAN_ESTUDIO PRIMARY KEY (ID_PLAN_ESTUDIO)
);

CREATE TABLE CARRERA_PLAN_ESTUDIO (
    ID_CARRERA_PLAN_ESTUDIO         NUMBER NOT NULL,
    CARRERA_ID_CARRERA              NUMBER NOT NULL,
    PLAN_ESTUDIO_ID_PLAN_ESTUDIO    NUMBER NOT NULL,
    CONSTRAINT PK_CARRERA_PLAN_ESTUDIO PRIMARY KEY (ID_CARRERA_PLAN_ESTUDIO),
    CONSTRAINT FK_CPE_CARRERA      FOREIGN KEY (CARRERA_ID_CARRERA)           REFERENCES CARRERA(ID_CARRERA),
    CONSTRAINT FK_CPE_PLAN_ESTUDIO FOREIGN KEY (PLAN_ESTUDIO_ID_PLAN_ESTUDIO) REFERENCES PLAN_ESTUDIO(ID_PLAN_ESTUDIO)
);

-- ============================================================
-- 11. TRIGGERS (auto-incremento para inserts sin ID)
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_PERMISOSROL_BI
BEFORE INSERT ON PERMISOSROL
FOR EACH ROW
WHEN (NEW.ID_PERMISOSROL IS NULL)
BEGIN
    :NEW.ID_PERMISOSROL := SEQ_PERMISOSROL.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_PLAN_ESTUDIO_BI
BEFORE INSERT ON PLAN_ESTUDIO
FOR EACH ROW
WHEN (NEW.ID_PLAN_ESTUDIO IS NULL)
BEGIN
    :NEW.ID_PLAN_ESTUDIO := SEQ_PLAN_ESTUDIO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CPE_BI
BEFORE INSERT ON CARRERA_PLAN_ESTUDIO
FOR EACH ROW
WHEN (NEW.ID_CARRERA_PLAN_ESTUDIO IS NULL)
BEGIN
    :NEW.ID_CARRERA_PLAN_ESTUDIO := SEQ_CARRERA_PLAN_ESTUDIO.NEXTVAL;
END;
/

-- ============================================================
-- 12. VISTAS
-- ============================================================

-- Vista para el portal de alumnos y reportes
CREATE OR REPLACE VIEW V_REPORTE_ALUMNOS_RESERVAS AS
SELECT
    u.ID_USUARIO,
    u.NOMBRE_USUARIO,
    u.EMAIL_USUARIO,
    e.ID_EXAMEN,
    e.NOMBRE_EXAMEN,
    r.ID_RESERVA,
    r.FECHA_RESERVA,
    (SELECT m2.INICIO_MODULO
     FROM MODULO m2
     JOIN RESERVAMODULO rm2 ON rm2.MODULO_ID_MODULO = m2.ID_MODULO
     WHERE rm2.RESERVA_ID_RESERVA = r.ID_RESERVA
       AND m2.ORDEN = (SELECT MIN(m3.ORDEN) FROM MODULO m3 JOIN RESERVAMODULO rm3 ON rm3.MODULO_ID_MODULO = m3.ID_MODULO WHERE rm3.RESERVA_ID_RESERVA = r.ID_RESERVA)
    ) AS HORA_INICIO,
    (SELECT m2.FIN_MODULO
     FROM MODULO m2
     JOIN RESERVAMODULO rm2 ON rm2.MODULO_ID_MODULO = m2.ID_MODULO
     WHERE rm2.RESERVA_ID_RESERVA = r.ID_RESERVA
       AND m2.ORDEN = (SELECT MAX(m3.ORDEN) FROM MODULO m3 JOIN RESERVAMODULO rm3 ON rm3.MODULO_ID_MODULO = m3.ID_MODULO WHERE rm3.RESERVA_ID_RESERVA = r.ID_RESERVA)
    ) AS HORA_FIN,
    s.NOMBRE_SALA,
    est_e.NOMBRE_ESTADO AS ESTADO_EXAMEN,
    est_r.NOMBRE_ESTADO AS ESTADO_RESERVA,
    r.ESTADO_CONFIRMACION_DOCENTE,
    a.NOMBRE_ASIGNATURA,
    sec.NOMBRE_SECCION,
    c.NOMBRE_CARRERA,
    j.NOMBRE_JORNADA,
    sede.ID_SEDE,
    esc.ID_ESCUELA,
    c.ID_CARRERA,
    a.ID_ASIGNATURA,
    sec.ID_SECCION,
    j.ID_JORNADA
FROM USUARIOSECCION us
JOIN USUARIO  u    ON us.USUARIO_ID_USUARIO      = u.ID_USUARIO
JOIN SECCION  sec  ON us.SECCION_ID_SECCION       = sec.ID_SECCION
JOIN ASIGNATURA a  ON sec.ASIGNATURA_ID_ASIGNATURA = a.ID_ASIGNATURA
JOIN CARRERA  c    ON a.CARRERA_ID_CARRERA        = c.ID_CARRERA
JOIN ESCUELA  esc  ON c.ESCUELA_ID_ESCUELA        = esc.ID_ESCUELA
JOIN SEDE     sede ON esc.SEDE_ID_SEDE            = sede.ID_SEDE
JOIN JORNADA  j    ON sec.JORNADA_ID_JORNADA      = j.ID_JORNADA
JOIN EXAMEN   e    ON e.SECCION_ID_SECCION        = sec.ID_SECCION
JOIN ESTADO   est_e ON e.ESTADO_ID_ESTADO         = est_e.ID_ESTADO
JOIN RESERVA  r    ON r.EXAMEN_ID_EXAMEN          = e.ID_EXAMEN
JOIN SALA     s    ON r.SALA_ID_SALA              = s.ID_SALA
JOIN ESTADO   est_r ON r.ESTADO_ID_ESTADO         = est_r.ID_ESTADO;

-- Vista para reportes detallados de exámenes
CREATE OR REPLACE VIEW V_REPORTE_EXAMENES_DETALLADO AS
SELECT
    e.ID_EXAMEN,
    e.NOMBRE_EXAMEN,
    e.INSCRITOS_EXAMEN,
    e.TIPO_PROCESAMIENTO_EXAMEN,
    e.PLATAFORMA_PROSE_EXAMEN,
    e.SITUACION_EVALUATIVA_EXAMEN,
    e.CANTIDAD_MODULOS_EXAMEN,
    est_e.ID_ESTADO,
    est_e.NOMBRE_ESTADO          AS NOMBRE_ESTADO_EXAMEN,
    r.ID_RESERVA,
    r.FECHA_RESERVA,
    est_r.NOMBRE_ESTADO          AS NOMBRE_ESTADO_RESERVA,
    r.ESTADO_CONFIRMACION_DOCENTE,
    s.ID_SALA,
    s.NOMBRE_SALA,
    s.CAPACIDAD_SALA,
    sec.ID_SECCION,
    sec.NOMBRE_SECCION,
    a.ID_ASIGNATURA,
    a.NOMBRE_ASIGNATURA,
    c.ID_CARRERA,
    c.NOMBRE_CARRERA,
    esc.ID_ESCUELA,
    esc.NOMBRE_ESCUELA,
    esc.COLOR_BACKGROUND,
    esc.COLOR_BORDER,
    sede.ID_SEDE,
    sede.NOMBRE_SEDE,
    j.ID_JORNADA,
    j.NOMBRE_JORNADA,
    (SELECT LISTAGG(TO_CHAR(rd.USUARIO_ID_USUARIO), ',') WITHIN GROUP (ORDER BY rd.USUARIO_ID_USUARIO)
     FROM RESERVA_DOCENTES rd
     WHERE rd.RESERVA_ID_RESERVA = r.ID_RESERVA) AS ID_DOCENTE,
    (SELECT LISTAGG(u2.NOMBRE_USUARIO, ', ') WITHIN GROUP (ORDER BY u2.NOMBRE_USUARIO)
     FROM RESERVA_DOCENTES rd2
     JOIN USUARIO u2 ON rd2.USUARIO_ID_USUARIO = u2.ID_USUARIO
     WHERE rd2.RESERVA_ID_RESERVA = r.ID_RESERVA) AS NOMBRE_DOCENTES
FROM EXAMEN e
JOIN ESTADO   est_e ON e.ESTADO_ID_ESTADO         = est_e.ID_ESTADO
JOIN SECCION  sec   ON e.SECCION_ID_SECCION        = sec.ID_SECCION
JOIN ASIGNATURA a   ON sec.ASIGNATURA_ID_ASIGNATURA = a.ID_ASIGNATURA
JOIN CARRERA  c     ON a.CARRERA_ID_CARRERA        = c.ID_CARRERA
JOIN ESCUELA  esc   ON c.ESCUELA_ID_ESCUELA        = esc.ID_ESCUELA
JOIN SEDE     sede  ON esc.SEDE_ID_SEDE            = sede.ID_SEDE
JOIN JORNADA  j     ON sec.JORNADA_ID_JORNADA      = j.ID_JORNADA
LEFT JOIN RESERVA r      ON r.EXAMEN_ID_EXAMEN     = e.ID_EXAMEN
LEFT JOIN ESTADO  est_r  ON r.ESTADO_ID_ESTADO     = est_r.ID_ESTADO
LEFT JOIN SALA    s      ON r.SALA_ID_SALA         = s.ID_SALA;

-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================
-- Credenciales del administrador:
--   Email:    admin@examenes.cl
--   Password: Admin123.
--
-- IMPORTANTE: Agregar en el .env raíz para el correo:
--   EMAIL_USER=tu-correo@gmail.com
--   EMAIL_PASSWORD=tu-clave-de-aplicacion-gmail
-- ============================================================
